// Auto generated by resx-to-ts-json (npm package, modified by GARAIO)

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export class VueResources {
  public static readonly Counter_Title = `VueResources.Counter_Title`;
  public static readonly Counter_Text = `VueResources.Counter_Text`;
}
